version: '3'
services:
    jsreports1:
        build: ./jsreports
        container_name: jsreports1
        ports:
            - "5488:5488"
        volumes:
            - ./jsreports/data:/app/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        networks:
            - bluebook_bluebook-net
    jsreports2:
        build: ./jsreports
        container_name: jsreports2
        ports:
            - "5489:5488"
        volumes:
            - ./jsreports/data2:/app/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        networks:
            - bluebook_bluebook-net
    jsreports3:
        build: ./jsreports
        container_name: jsreports3
        ports:
            - "5490:5488"
        volumes:
            - ./jsreports/data3:/app/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        networks:
            - bluebook_bluebook-net
    jsreports4:
        build: ./jsreports
        container_name: jsreports4
        ports:
            - "5491:5488"
        volumes:
            - ./jsreports/data4:/app/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        networks:
            - bluebook_bluebook-net
networks:
    bluebook_bluebook-net:
        external: true 
